In [18]:
import pandas as pd

We can create dataframe using lists as well as dictionaries

In [19]:
data_list = {"Name":["Rohit","Sittal","Rajiv","Sandesh","Anjil"],
"Age":[18,20,22,24,23],
"City":["Butwal","Jungle","Home","College","Jorpati"],
"Salary":[60000,70000,80000,32000,25000]}

In [20]:
data = pd.DataFrame(data_list)
data

      Name  Age     City  Salary
0    Rohit   18   Butwal   60000
1   Sittal   20   Jungle   70000
2    Rajiv   22     Home   80000
3  Sandesh   24  College   32000
4    Anjil   23  Jorpati   25000

In [21]:
data_lyst = [["rohit","sittal"],
             [18,20],
            ["Butwal","Jungle"],
            [60000,70000]]
contents = ["Name","Age","City","Salary"]
pd.DataFrame(data_lyst,contents)

             0       1
Name     rohit  sittal
Age         18      20
City    Butwal  Jungle
Salary   60000   70000

In [22]:
data[["Name","Age"]] #selection of column

      Name  Age
0    Rohit   18
1   Sittal   20
2    Rajiv   22
3  Sandesh   24
4    Anjil   23

In [23]:
data["Designation"]= ["Doctor","Engineer","Pilot","Designer","Coder"]
data  #inserting new columns

      Name  Age     City  Salary Designation
0    Rohit   18   Butwal   60000      Doctor
1   Sittal   20   Jungle   70000    Engineer
2    Rajiv   22     Home   80000       Pilot
3  Sandesh   24  College   32000    Designer
4    Anjil   23  Jorpati   25000       Coder

In [24]:
data.drop("Designation",axis =1 )
#deleting a column

      Name  Age     City  Salary
0    Rohit   18   Butwal   60000
1   Sittal   20   Jungle   70000
2    Rajiv   22     Home   80000
3  Sandesh   24  College   32000
4    Anjil   23  Jorpati   25000

In [25]:
# data.drop(0,axis = 0)
# deleting a row

In [26]:
data.loc[[0,1]]

     Name  Age    City  Salary Designation
0   Rohit   18  Butwal   60000      Doctor
1  Sittal   20  Jungle   70000    Engineer

In [30]:
data.iloc[0:3]

     Name  Age    City  Salary Designation
0   Rohit   18  Butwal   60000      Doctor
1  Sittal   20  Jungle   70000    Engineer
2   Rajiv   22    Home   80000       Pilot

In [31]:
data.loc[[0,1,3]][["City","Salary"]]

      City  Salary
0   Butwal   60000
1   Jungle   70000
3  College   32000

In [35]:
#conditional selection
data[(data["Age"]>20)  & (data["City"]=="Jorpati")]

    Name  Age     City  Salary Designation
4  Anjil   23  Jorpati   25000       Coder